//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFBasicTutorials
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolDbEntities : DbContext
    {
        public SchoolDbEntities()
            : base("name=SchoolDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<standard> standards { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentaddress> studentaddresses { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
    }
}
